### ISSUE TITLE
image_mask_name = image_name.split('.')[0] + '_mask.tif'

### ISSUE THREAD

**Issue by qew21** [JenifferWuUCLA/pulmonary-nodules-segmentation#1]
`image_mask_name = image_name.split('.')[0] + '_mask.tif'`
No '*tif' was generated in this branch, is it the same as
`
cv2.imwrite(os.path.join(self.tmp_jpg_workspace, "masks_%s_%04d_%04d_%04d_o.jpg" % (cur_row["seriesuid"],
  | fcount, node_idx, i_z)), nodule_mask)
`
 in 'train_dataset_preprocessing_2DUnet.py'? Thank you.

**Comment by JenifferWuUCLA** [comment]
Hi, 
    Tagged Image File Format, abbreviated TIFF or TIF, is a computer file format for storing raster graphics images. But, in this project, I preprocessed the lung CT image into a slice of JPG images.
