### ISSUE TITLE
Why no nodules have been found in test prediction images after unet training?

### ISSUE THREAD

**Issue by BUCT-wayne** [JenifferWuUCLA/pulmonary-nodules-segmentation#2]
Hi!I have trained the unet with DSB3Tutorial,but I meet the same problem as you.The prediction image is all black and there are no nodules.
Do you solve it now?Can you give me some suggestions?
Thanks!

**Comment by JenifferWuUCLA** [comment]
Hi,
    The problem has been solved, and I have gotten predicted nodules after segmentation. The program generates predicted coordinates at the same time.
    I wish it will give you some clues. 
Good luck!
