### ISSUE TITLE
how to process tianchi_segment_lung_ROI's data

### ISSUE THREAD

**Issue by qiuliwang** [JenifferWuUCLA/pulmonary-nodules-segmentation#3]
I see you load data from "images_0004_0023.npy". I try to modify dicom data into .npy file, but the result is very bad. 
Could you please tell me, how to make a file like "images_0004_0023.npy"

**Comment by JenifferWuUCLA** [comment]
Hello, 
Firstly, the program, which is called *_dataset_segment_lung_ROI.py, has deprecated. I used these two programs in the early project of "Lung nodule Intelligent diagnosis," but now I'm no longer using them in my experiments.
Secondly, the file "images_0004_0023.npy" is generated through mask extraction.  
Lastly, the medical CT images I used is .mhd format data, but it is not dicom data.
